### ISSUE TITLE
Registrazione, Login, Geoposizione

### ISSUE THREAD

**Issue by scaruso** [mfredella/SocialBikeKeeper#11]
Creare un sistema che permetta a un utente di registrarsi, loggarsi e visualizzare la propria posizione su di una Google Map.

**Comment by mariannafucci** [comment]
Funzioni di registrazione e login realizzate attraverso l'uso del server Altervista e degli script php con cui gestiamo il database.
Per quanto riguarda la geoposizione abbiamo utilizzato una google map creando una chiave per abilitare l'API corrispondente.
