### ISSUE TITLE
Lancio di una sfida

### ISSUE THREAD

**Issue by mariannafucci** [mfredella/SocialBikeKeeper#13]
Si vuole aggiungere una nuova funzionalità, ovvero il lancio di una sfida.

**Comment by scaruso** [comment]
La funzionalità è stata aggiunta utilizzando un IntentService che, ogni 30 secondi, interrogherà il database per lanciare notifiche che informeranno i ciclisti coinvolti nella sfida.

**Comment by mfredella** [comment]
Effettuando test black box è sorto un problema: nel caso in cui uno dei due ciclisti conivolti nella sfida chiuda l'app, questa crasha.

**Comment by mariannafucci** [comment]
Problema risolto aggiungendo uno stato della sfida in cui se uno dei due sfidanti esca dall'app, volontariamente o meno, il sistema notificherà all'altro la vittoria a tavolino.
